global_costmap:
  global_frame: map     # 全局坐标系
  robot_base_frame: base_link
  update_frequency: 1.0 # 全局地图更新频率（不需要太快）
  publish_frequency: 1.0
  static_map: true      # 使用 map_server 提供的静态地图

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}