local_costmap:
  global_frame: odom    # 局部规划通常基于里程计
  robot_base_frame: base_link
  update_frequency: 5.0 # 更新频率要高，应对动态障碍物
  publish_frequency: 5.0
  static_map: false     # 局部地图随机器人移动
  rolling_window: true  # 滚动窗口模式
  width: 3.0            # 局部地图范围 3x3 米
  height: 3.0
  resolution: 0.05

  plugins:
    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}